name: AdhaEvent
version: '${project.version}'
main: lunatic.adhaevent.Main
api-version: '1.20'
softdepend:  [ ProtocolLib , ChronoCore, RedProtect]
commands:
  adhashop:
    description: Open shop
    permission: adha.shop
  adhareload:
    description: Reload
    permission: adha.reload